---
# Install NFS Server
- name: Install nfs-utils package
  dnf:
    name: nfs-utils
    state: present

# Create the NFS Share Directory
- name: Ensure NFS share directory exists
  file:
    path: /shares/registry
    state: directory
    owner: nobody
    group: nobody
    mode: '0770'

- name: Ensure NFS share directory /shares/csi exists
  file:
    path: /shares/csi
    state: directory
    owner: nobody
    group: nobody
    mode: '0770'

# Deploy NFS Exports Configuration
- name: Ensure /etc/exports file has proper ownership and permissions
  file:
    path: /etc/exports
    owner: root
    group: root
    mode: '0770'
  notify:
    - Reload NFS Exports

# Enable and Start NFS Services
- name: Enable and start NFS-related services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nfs-server
    - rpcbind
    - nfs-mountd

# Restart NFS Server to apply new configuration
- name: Restart NFS server to apply new configuration
  service:
    name: nfs-server
    state: restarted

# Validate the NFS Share is Exported
- name: Verify the NFS share is exported
  shell: exportfs
  register: nfs_export_status
  changed_when: false

- name: Debug NFS export validation
  debug:
    msg: "NFS exports: {{ nfs_export_status.stdout_lines }}"

# Validate Permissions and Ownership of the Share Directory
- name: Validate permissions of NFS share directory
  stat:
    path: /shares/registry
  register: registry_dir_status

- name: Debug directory validation
  debug:
    msg:
      - "Owner: {{ registry_dir_status.stat.pw_name }}"
      - "Group: {{ registry_dir_status.stat.gr_name }}"
      - "Permissions: {{ registry_dir_status.stat.mode }}"
      - "Directory exists: {{ registry_dir_status.stat.exists }}"
