---
- name: Calculate PTR record location
  ansible.builtin.set_fact:
    ip_parts: "{{ ip_address.split('.') }}"

- name: Delete PTR record
  ansible.builtin.uri:
    url: "{{ powerdns_base_url }}/zones/{{ ip_parts[2] }}.{{ ip_parts[1] }}.{{ ip_parts[0] }}.in-addr.arpa."
    method: PATCH
    headers:
      X-API-Key: "{{ powerdns_api_key }}"
    body_format: json
    body:
      rrsets:
      - name: "{{ ip_parts[3] }}.{{ ip_parts[2] }}.{{ ip_parts[1] }}.{{ ip_parts[0] }}.in-addr.arpa."
        type: "PTR"
        changetype: "DELETE"
    status_code: [ 204, 404 ] # 404 is OK if PTR doesn't exist
