---
- name: Remove records from zone
  ansible.builtin.uri:
    url: "{{ powerdns_base_url }}/zones/{{ zone_id }}"
    method: PATCH
    headers:
      X-API-Key: "{{ powerdns_api_key }}"
    body_format: json
    body: "{{ lookup('template', 'destroy_records.j2') }}"
    status_code: 204
