---
# PowerDNS HTTP API
powerdns_api_host: "localhost"
powerdns_api_port: 8081
powerdns_api_key: "gaMare239"
powerdns_server_id: "localhost"
powerdns_base_url: "http://{{ powerdns_api_host }}:{{ powerdns_api_port }}/api/v1/servers/{{ powerdns_server_id }}"

# Default TTL
default_ttl: 3600
