---
# Install HAProxy
- name: Install HAProxy package
  dnf:
    name: haproxy
    state: present

# Ensure required directories exist before starting HAProxy
- name: Ensure /etc/selinux/custom directory exists
  file:
    path: /etc/selinux/custom
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Ensure logging directory exists
  file:
    path: /var/log/haproxy
    state: directory
    owner: haproxy
    group: haproxy
    mode: '0770'

- name: Ensure /etc/haproxy directory exists
  file:
    path: /etc/haproxy
    state: directory
    owner: root
    group: root
    mode: '0770'

- name: Ensure HAProxy log files exist
  file:
    path: "{{ item }}"
    state: touch
    owner: haproxy
    group: haproxy
    mode: '0644'
  loop:
    - /var/log/haproxy/haproxy.log
    - /var/log/haproxy/haproxy-errors.log

- name: Ensure HAProxy chroot directory exists
  file:
    path: /var/lib/haproxy/dev
    state: directory
    owner: root
    group: root
    mode: '0770'

# Enable and start HAProxy service
- name: Enable and start HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes
