---
# Compute cluster specifications

- name: Build | Cluster spec
  set_fact:
    cluster_spec:
      name: "{{ vcenter_cluster_name }}"
      datacenter_name: "{{ extensionInstanceVariables.vcenter_datacenter_name | default(sddc_id ~ '-dc1') }}"
      evc_mode: "{{ extensionInstanceVariables.cluster_evc_mode | default('') }}"
      resource_pool_specs_consolidated:
        - name: "{{ management_resource_pool_name }}"
          cpu_limit: -1
          cpu_reservation_expandable: true
          cpu_reservation_mhz: 0
          cpu_reservation_percentage: 0
          cpu_shares_level: high
          cpu_shares_value: 0
          memory_limit: -1
          memory_reservation_expandable: true
          memory_reservation_mb: 0
          memory_reservation_percentage: 0
          memory_shares_level: normal
          memory_shares_value: 0
          type: management
        - name: "{{ networking_resource_pool_name }}"
          cpu_shares_level: high
          cpu_shares_value: 0
          memory_shares_value: 0
          cpu_reservation_percentage: 0
          memory_limit: -1
          memory_reservation_percentage: 0
          cpu_reservation_expandable: true
          memory_reservation_expandable: true
          memory_shares_level: normal
          cpu_limit: -1
          type: network
        - name: "{{ compute_user_vm_resource_pool_name }}"
          cpu_shares_level: normal
          cpu_shares_value: 0
          memory_shares_value: 0
          cpu_reservation_percentage: 0
          memory_limit: -1
          memory_reservation_percentage: 0
          cpu_reservation_expandable: true
          memory_reservation_expandable: true
          memory_shares_level: normal
          cpu_limit: -1
          type: compute
        - name: "{{ compute_user_edge_resource_pool_name }}"
          cpu_shares_level: high
          cpu_shares_value: 0
          memory_shares_value: 0
          cpu_reservation_percentage: 0
          memory_limit: -1
          memory_reservation_percentage: 0
          cpu_reservation_expandable: true
          memory_reservation_expandable: true
          memory_shares_level: normal
          cpu_limit: -1
          type: compute
