---
# Storage specifications

- name: Build | VSAN spec
  set_fact:
    vsan_spec:
      datastore_name: "{{ extensionInstanceVariables.vsan_datastore_name | default(sddc_id + '-cl1-ds1') }}"
      vsan_dedup: "{{ extensionInstanceVariables.vsan_dedup_enabled | default(false) | bool }}"
      esa_config: "{{ extensionInstanceVariables.vsan_esa_enabled | default(false) | bool }}"
      failures_to_tolerate: "{{ configVars.vsan_failures_to_tolerate | default(1) }}"
