---
# https://developer.broadcom.com/xapis/vmware-cloud-foundation-api/latest/clusters/
- name: SDDC Manager API | Get the Clusters
  ansible.builtin.uri:
    url: "https://{{ sddc_manager_spec.ipv4_address }}/v1/clusters"
    method: GET
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ sddc_manager_access_token }}"
    status_code:
      - 200
    follow_redirects: all
    return_content: yes
    validate_certs: "{{ sddc_manager.validate_certs }}"
  register: sddc_manager_clusters_response
  delegate_to: localhost

- name: Debug SDDC Manager Clusters Response
  ansible.builtin.debug:
    var: sddc_manager_clusters_response
  when: sddc_manager.api_call_debug | bool
