---
# Common initialization for Cloud-Builder verification tasks via VMware Tools

- name: Assert required CBA variables are defined
  ansible.builtin.assert:
    that:
      - cba.ipv4_address is defined
      - cba.hostname is defined
      - cba.hostname_fqdn is defined
      - cba.root_password is defined
    fail_msg: "cba.hostname, cba.hostname_fqdn, cba.ipv4_address and cba.root_password must be defined."

- name: Set ESXi connection facts
  ansible.builtin.set_fact:
    target_esxi_hostname: "{{ ansible_host }}"
    target_esxi_username: "{{ ansible_user | default('root') }}"
    target_esxi_password: "{{ ansible_password }}"
  delegate_to: localhost

- name: Wait for VMware Tools to be running
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ target_esxi_hostname }}"
    username: "{{ target_esxi_username }}"
    password: "{{ target_esxi_password }}"
    validate_certs: "{{ cba.validate_certs | default(false) }}"
    name: "{{ cba.hostname }}"
    timeout: 600
  delegate_to: localhost
