---
# Verify Cloud-Builder deployment and configuration via VMware Tools

- name: Verify Cloud-Builder NTP synchronization via VMware Tools
  ansible.builtin.include_tasks: cba-checks/verify-ntp-vmtools.yaml
  tags: [cba-checks, cba-ntp-verify]

- name: Include Cloud-Builder DNS verification via VMware Tools
  ansible.builtin.include_tasks: cba-checks/verify-dns-vmtools.yaml
  tags: [cba-checks, cba-dns-verify]
