---
debug_vmnic_mapping: "{{ extensionInstanceVariables.get('validation_debug', false) | bool }}"

sddc_id: "{{ extensionInstanceRecordSet.sddc_id | default(extension_instance_id ~ '-m', true) }}"
management_pool_name: "{{ extensionInstanceVariables.management_pool_name | default(sddc_id ~ '-np1', true) }}"
vcenter_cluster_name: "{{ extensionInstanceVariables.vcenter_cluster_name | default(sddc_id ~ '-cl1', true) }}"
management_vm_folder_name: "{{ extensionInstanceVariables.management_vm_foldername | default('m-fd-mgmt', true) }}"
networking_vm_folder_name: "{{ extensionInstanceVariables.networking_vm_foldername | default('m-fd-nsx', true) }}"
management_resource_pool_name: "{{ extensionInstanceVariables.management_resource_pool_name | default(sddc_id ~ '-cl1-rp-sddc-mgmt', true) }}"
networking_resource_pool_name: "{{ extensionInstanceVariables.networking_resource_pool_name | default(sddc_id ~ '-cl1-rp-sddc-edge', true) }}"
compute_user_vm_resource_pool_name: "{{ extensionInstanceVariables.compute_user_vm_resource_pool_name | default(sddc_id ~ '-cl1-rp-user-vm', true) }}"
compute_user_edge_resource_pool_name: "{{ extensionInstanceVariables.compute_user_edge_resource_pool_name | default(sddc_id ~ '-cl1-rp-user-edge', true) }}"

vm_management_portgroup_name: "{{ extensionInstanceVariables.vm_management_portgroup_name | default(sddc_id ~ '-cl1-vds1-vm-mgmt', true) }}"
esxi_management_portgroup_name: "{{ extensionInstanceVariables.esxi_management_portgroup_name | default(sddc_id ~ '-cl1-vds1-esxi-mgmt', true) }}"
vmotion_portgroup_name: "{{ extensionInstanceVariables.vmotion_portgroup_name | default(sddc_id ~ '-cl1-vds1-vmotion', true) }}"
vsan_portgroup_name: "{{ extensionInstanceVariables.vsan_portgroup_name | default(sddc_id ~ '-cl1-vds1-vsan', true) }}"

nsx_host_overlay_ip_pool_name: "{{ extensionInstanceVariables.nsx_host_overlay_ip_pool_name | default(sddc_id ~ '-cl1-tep1', true) }}"
