---
- name: VCF Installer API CALL | Obtain access token
  ansible.builtin.uri:
    url: "https://{{ installer.ipv4_address }}/v1/tokens"
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    body_format: json
    body:
      username: "admin@local"
      password: "{{ installer.admin_password }}"
    status_code: [200, 201]
    validate_certs: "{{ installer.validate_certs }}"
  register: installer_token_response
  retries: 5
  delay: 10
  until: installer_token_response is succeeded
  no_log: "{{ not (vcf.validation_debug | default(false) | bool) }}"
  delegate_to: localhost

- name: Set installer auth headers
  ansible.builtin.set_fact:
    installer_auth_headers:
      Accept: "application/json"
      Content-Type: "application/json"
      Authorization: "Bearer {{ installer_token_response.json.accessToken }}"
