---
# =====================================================
# OpenShift, and Download Setup
# =====================================================

- name: Ensure necessary packages for downloading and unarchiving are installed
  dnf:
    name:
      - wget
      - tar
      - gzip
      - curl
      - git
      - vim
      - coreutils
    state: latest

- name: Ensure the OpenShift download directory exists
  file:
    path: "{{ download_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0770'

- name: Export OC_EDITOR and KUBE_EDITOR to vim
  lineinfile:
    path: /etc/profile.d/oc_kube_editor.sh
    line: "{{ item }}"
    create: yes
    mode: '0755'
  loop:
    - 'export OC_EDITOR="vim"'
    - 'export KUBE_EDITOR="vim"'

- name: Define downloads variable
  set_fact:
    downloads:
      - name: OpenShift Client
        url: "{{ openshift_client_url }}"
        dest: "{{ download_dir }}/openshift-client-linux.tar.gz"
        extract_to: /usr/local/bin
      - name: OpenShift Installer
        url: "{{ openshift_installer_url }}"
        dest: "{{ download_dir }}/openshift-install-linux.tar.gz"
        extract_to: /usr/local/bin

- name: Download archives
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop: "{{ downloads }}"
  loop_control:
    loop_var: item

- name: Unarchive downloads
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ item.extract_to }}"
    remote_src: yes
  loop: "{{ downloads }}"
  loop_control:
    loop_var: item

- name: Remove downloaded archives
  file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ downloads }}"
  loop_control:
    loop_var: item

- name: Verify OpenShift CLI (oc) installation
  command: oc version --client
  register: oc_output

- name: Download RHCOS Metal Image
  get_url:
    url: "{{ rhcos_metal_image_url }}"
    dest: "{{ download_dir }}/{{ rhcos_version }}-x86_64-metal.x86_64.raw.gz"
    mode: '0644'


- name: Stop firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: stopped

- name: Disable firewalld service
  ansible.builtin.systemd:
    name: firewalld
    enabled: no
