---
- name: Generate timestamp
  ansible.builtin.set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Create Incus config directory if it does not exist
  ansible.builtin.file:
    path: "{{ incus_bootstrap_config_dir }}"
    state: directory
    mode: "0700"
    owner: root
    group: root
    recurse: true

- name: Create Incus init pressed config file
  ansible.builtin.template:
    src: incus-cluster-init-bootstrap-first-server-config.yaml.j2
    dest: "{{ incus_bootstrap_config_dir }}/incus-init-pressed-{{ timestamp }}.yaml"
    mode: "0644"
    owner: root
    group: root

- name: Initialize Incus cluster
  ansible.builtin.shell:
    cmd: "set -o pipefail && cat {{ incus_bootstrap_config_dir }}/incus-init-pressed-{{ timestamp }}.yaml | incus admin init --preseed"
    executable: /bin/bash
  register: incus_cluster_init
  changed_when: incus_cluster_init.rc == 0
