---
- name: Set fact | SDDC Manager parameters
  set_fact:
    sddc_manager:
      validate_certs: "{{ extensionInstanceVariables.sddc_manager_validate_certs | default('no') }}"
      access_token_debug: "{{ extensionInstanceVariables.sddc_manager_access_token_debug | default(extensionInstanceVariables.validation_debug | default(false) | bool) | bool }}"
      api_username: "{{ management_server_instance_group_custom_variables.vcenter_sso_admin_username | default('administrator@vsphere.local') }}"
      api_password: "{{ psc_specs.sso_admin_password }}"
      api_call_debug: "{{ extensionInstanceVariables.sddc_manager_api_call_debug | default(extensionInstanceVariables.validation_debug | default(false) | bool) | bool }}"

- name: SDDC Manager API | Obtain access token
  ansible.builtin.uri:
    url: "https://{{ sddc_manager_spec.hostname }}/v1/tokens"
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    body_format: json
    body:
      username: "{{ sddc_manager.api_username }}"
      password: "{{ sddc_manager.api_password }}"
    status_code:
      - 200
    follow_redirects: all
    return_content: yes
    validate_certs: "{{ sddc_manager.validate_certs }}"
  register: sddc_manager_api_token_response
  vars:
    ansible_python_interpreter: /bin/python

- name: Set access token fact
  set_fact:
    sddc_manager_access_token: "{{ sddc_manager_api_token_response.json.accessToken }}"

- name: Debug SDDC Manager Access Token
  ansible.builtin.debug:
    msg: "SDDC Manager Access Token: {{ sddc_manager_access_token }}"
  when: sddc_manager.access_token_debug | bool
