---
# Increase cluster size by adding one or more nodes.
- name: Scale out cluster
  hosts: incus_scale_out
  become: true
  tasks:
    - name: Scale out cluster
      ansible.builtin.include_role:
        name: incus
        tasks_from: incus-scale-out.yaml
      when: groups.get('incus_scale_out', []) | length > 0

# Decrease cluster size by removing/decommissioning one or more nodes.
- name: Scale in cluster | one node at a time
  hosts: incus_scale_in
  become: true
  serial: 1
  tasks:
    - name: Scale in cluster
      ansible.builtin.include_role:
        name: incus
        tasks_from: incus-scale-in.yaml
      when: groups.get('incus_scale_in', []) | length > 0
