---
- name: Setup ESXi Hosts
  hosts: all
  gather_facts: false
  become: true
  become_user: root
  collections:
    - community.vmware
  roles:
    - role: esxi
      tags: esxi

- name: Deploy VMware Cloud Foundation
  hosts: management[0]
  gather_facts: false
  collections:
    - community.vmware
  roles:
    - role: vcf
      tags: vcf
